name: Playwright Tests

on:
  schedule:
    - cron: "00 00 * * *"   # UTC midnight
  workflow_dispatch:
    inputs:
      environment:
        description: "Target environment"
        required: true
        type: choice
        default: STAGING
        options: [DEV, STAGING, PROD]
      workers:
        description: "Playwright workers (parallelism)"
        required: false
        default: "4"
        type: number
      project:
        description: "Playwright project (browser)"
        required: false
        default: chromium
        type: choice
        options: [chromium, firefox, webkit]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  test:
    name: Run Playwright Tests
    timeout-minutes: 60
    runs-on: ubuntu-latest

    container:
      image: mcr.microsoft.com/playwright:v1.55.1-jammy
      options: --ipc=host

    # Use the selected environment so its environment-scoped secrets are available
    environment: ${{ inputs.environment || 'STAGING' }}

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: Run Playwright tests
        env:
          # If use GitHub Environments (DEV/STAGING/PROD), put a secret named BASE_URL in each.
          BASE_URL: ${{ secrets.BASE_URL }}
        run: >
          npx playwright test
          --project=${{ inputs.project || 'chromium' }}
          --workers=${{ inputs.workers || '4' }}
          --reporter=html

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: playwright-report

  deploy:
    name: Deploy Report to GitHub Pages
    needs: test
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
